version: '3.1'

services:

  dbbed:
    image: mariadb:10.3
    container_name: dbbuild
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: build
      MYSQL_USER: build
      MYSQL_PASSWORD: mypasswd
      MYSQL_ROOT_HOST: 192.168.0.48/255.255.255.248
    ports:
      - "3500:3306"
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  mysql:
